import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Developer Raz || Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-violet-900 ">
        {/* hero section */}
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">Developedby</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500  text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Ramazan Aziz Bocuk
            </h2>
            <h3 className="text-xl  py-2 md:text-3xl">
              UX Developer and Designer
            </h3>
            <p className="text-medium py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto">
              Your friendly, neighborhood beard enthusiast and experience
              designer. Bent on empowering all types of people through design.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-5 text-gray-600">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-98 ">
            <Image src={deved} layout="fill" objectFit="cover" />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1">Services I offer</h3>
            <p className="text-medium py-5 leading-8 text-gray-800">
              My goal is to create value in all my projects. Focusing my
              customer targets and make them a website that will give them a
              professional digital identity.
            </p>
            <span className="text-teal-500">As a designer </span>
            I’m updating my customers in each step of the project.I’m always
            there support, offer{" "}
            <span className="text-teal-500">the best solutions</span>{" "}
            <p>that they are successfully achieving their business goals.</p>
          </div>
          <div className="lg:flex gap-10">
            {/* work1 */}
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={design} width={100} height={100} />
              <h3 className="text-large font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                One of My values as Freelancer is ‘Beauty in Simplicity’ because
                I love making things simple, intuitive and expertly crafted.
                Foremost to that is exceptional user experience.
              </p>
              <h4 className="text-teal-600 py-2">Design Tools</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">XD</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            {/* work2 */}
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={code} width={100} height={100} />
              <h3 className="text-large font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                One of My values as Freelancer is ‘Beauty in Simplicity’ because
                I love making things simple, intuitive and expertly crafted.
                Foremost to that is exceptional user experience.
              </p>
              <h4 className="text-teal-600 py-2">Design Tools</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">XD</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            {/* work3 */}
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-large font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                One of My values as Freelancer is ‘Beauty in Simplicity’ because
                I love making things simple, intuitive and expertly crafted.
                Foremost to that is exceptional user experience.
              </p>
              <h4 className="text-teal-600 py-2">Design Tools</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">XD</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
          </div>
        </section>

        {/* darkmode */}
        <section>
          <div>
            <h3 className="text-3xl font-medium pt-8 pb-2">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              All great products marry exceptional design with solid execution.
              I’m insatiably curious about what’s next in technology, but I will
              always strive to pick the right tools for the job.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web2}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web3}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web4}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web5}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web6}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
